version: "3.9"

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        container_name: nextjs
        restart: unless-stopped
        ports:
            - "3001:3000"
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules/
            - /usr/app/.next/
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

        # if you need to stop the containers run:
        # docker compose down --volumes
