version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/home/node/app

    # if you need to stop the containers run:
    # docker compose down --volumes

  db:
    # bitnami has Replica`s Configurations that matches MongoDB setup
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    # ports:
    #   - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379

volumes:
  mongodb_data:
    driver: local
